### ISSUE TITLE
Build docker image locally

### ISSUE THREAD

**Issue by dgarus** [pyrsia/pyrsia#1632]
### Steps taken/Steps to reproduce

We are doing
```
docker-compose up -d
```
and then the
```
docker-compose logs -f
```
shows 
![image](https://user-images.githubusercontent.com/25565200/219348739-ba162051-5685-432a-8313-c04c6e6917c5.png)

[Discussion](https://app.slack.com/client/TJWP1JXK6/C04QFFVLQ4Q)

### Expected Behavior

Pyrsia node should start successfully.

### Experienced Instance of the bug

Pyrsia: v0.2.4

**Comment by dgarus** [comment]
Possible solutions: 
1. 
Add this to the top of node-entrypoint.sh
```
if [ "${PYRSIA_BOOTDNS}" == "" ]; then
  PYRSIA_BOOTDNS=boot.pyrsia.link
fi
```

docker-compose.yml
```
services:
  pyrsia:
    environment: # Turn on debug
      - RUST_LOG=debug
      - PYRSIA_BOOTDNS=boot.pyrsia.link
    image: pyrsia/node
    build:
      context: .
      target: node
    stdin_open: true
    ports:
      - "7888:7888"
    volumes:
      - "pyrsia:/tmp"

volumes:
  pyrsia:
```
Remove command and add `PYRSIA_BOOTDNS` to the environment. But then it comes up.
