### ISSUE TITLE
Create a dockerized version of the Pyrsia node

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#224]
Following on an issue discovered on mac #203 a discussion started on whether we need a dockerized version of the Pyrsia node.

I'm creating this issue so it can be discussed and prioritized.

@chris-crone did some experiments on this in: https://github.com/chris-crone/pyrsia/commit/c2b7c7c4a1c3ea5880eb6145c26dc702d9d19a58 and I'm commenting it here so it doesn't get lost:

Using:
```
docker buildx bake
```

and a docker-compose.yml:
```
services:
  pyrsia:
    image: pyrsia/node
    command: -p 7878
    ports:
      - "7878:7878"
    volumes:
      - pyrsia:/tmp

volumes:
  pyrsia:
```

This brings up the Pyrsia node at port 7878
