### ISSUE TITLE
Create a docker-compose file to setup a local multi-node demo/test environment

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#560]
1. Create a docker-compose.yml file that:

* starts multiple Pyrsia nodes
* using either the published Pyrsia or a local build
* and connecting the nodes to each other
* possibly keeping state between restarts
* and ready to run the demo scenario

2. Document these steps in a tutorial like the demo/macos tutorial

**Comment by erwin1** [comment]
This is a good starting point but it needs fine-tuning and documentation

```
services:
  nodeA:
    image: pyrsia/node
    command: ["-H", "0.0.0.0", "-L", "/ip4/0.0.0.0/tcp/44000"]
    ports:
      - 7888:7888
    volumes:
      - "nodeA:/pyrsia"

  nodeB:
    depends_on:
      - nodeA
    image: pyrsia/node
    command: ["-H", "0.0.0.0", "-p", "7889", "--peer", "/dns4/nodea/tcp/44000"]
    ports:
      - 7889:7889
    volumes:
      - "nodeB:/pyrsia"

volumes:
  nodeA:
  nodeB:
```
